language: android
android:
  components:
    - tools
    - build-tools-29.0.0
    - android-29
before_install:
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.0"
jdk:
  - oraclejdk8
script:
  - ./gradlew clean build detekt
branches:
  except:
    - gh-pages
notifications:
  email: false
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
